# fmt: off
# ^ turn off black formatting
# to turn it on for any reason, use # fmt: on
from typing import Literal

ItemType = Literal[
    "posts",
    "playlists",
    "levels",
    "skins",
    "backgrounds",
    "effects",
    "particles",
    "engines",
    "replays",
    "rooms",
    "users",
]
ItemTypeExcludingRoom = Literal[
    "posts",
    "playlists",
    "levels",
    "skins",
    "backgrounds",
    "effects",
    "particles",
    "engines",
    "replays",
    "users",
]

ServerInfoButtonType = Literal[
    "authentication",
    "multiplayer",
    "post",
    "playlist",
    "level",
    "replay",
    "skin",
    "background",
    "effect",
    "particle",
    "engine",
    "configuration",
    "user",
]

AutoExit = Literal["off", "pass", "fullCombo", "allPerfect"]

Grade = Literal["allPerfect", "fullCombo", "pass", "fail"]

Icon = Literal[
    "advanced",
    "angleDown",
    "angleLeft",
    "angleRight",
    "anglesDown",
    "anglesLeft",
    "anglesRight",
    "anglesUp",
    "angleUp",
    "arrowDown",
    "arrowLeft",
    "arrowRight",
    "arrowUp",
    "award",
    "background",
    "bell",
    "bellSlash",
    "bookmark",
    "bookmarkHollow",
    "check",
    "clock",
    "comment",
    "crown",
    "customServer",
    "delete",
    "edit",
    "effect",
    "engine",
    "envelope",
    "envelopeOpen",
    "globe",
    "heart",
    "heartHollow",
    "hide",
    "information",
    "level",
    "lock",
    "medal",
    "message",
    "minus",
    "options",
    "particle",
    "pin",
    "player",
    "playlist",
    "plus",
    "post",
    "question",
    "ranking",
    "replay",
    "reply",
    "restore",
    "room",
    "search",
    "settings",
    "show",
    "shuffle",
    "skin",
    "star",
    "starHalf",
    "starHollow",
    "stopwatch",
    "tag",
    "thumbsDown",
    "thumbsDownHollow",
    "thumbsUp",
    "thumbsUpHollow",
    "trophy",
    "unlock",
    "xMark",
]

from helpers.sonolus_text import Text as Text  # noqa: F401
